nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/':
            allow_origin:
                - 'http://localhost:5173'
                - 'http://127.0.0.1:5173'
            allow_headers:
                - Content-Type
                - Authorization
                - X-Requested-With
            allow_methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
            allow_credentials: false
            max_age: 3600